<script>
  import SvelteMarkdown from "svelte-markdown";
  import Chip from "../../../lib/components/Chip.svelte";
  import dayjs from "dayjs";
  import relativeTime from "dayjs/plugin/relativeTime";
  dayjs.extend(relativeTime);

  export let data;
</script>

<svelte:head>
  <title>{data.human.name} | AsianAmericans.wiki</title>
</svelte:head>

<article class="max-w-2xl">
  <h1 class="text-2xl my-4">{data.human.name}</h1>
  <table
    class="table-auto w-full text-sm text-left text-gray-500 dark:text-gray-400"
  >
    {#if data.human.aliases}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >Aliases</th
        >
        <td>{data.human.aliases}</td>
      </tr>
    {/if}
    {#if data.human.dob}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >Born</th
        >
        <td>{data.human.dob}</td>
      </tr>
    {/if}
    {#if data.human.dod}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >Died</th
        >
        <td>{data.human.dod}</td>
      </tr>
    {/if}
    {#if data.human.ethnicity}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >Ethnicity</th
        >
        <td>
          <ul class="flex flex-row">
            {#each data.human.ethnicity as ethnicity}
              <li>
                <Chip><a href="/search?query={ethnicity}">{ethnicity}</a></Chip>
              </li>
            {/each}
          </ul></td
        >
      </tr>
    {/if}
    {#if data.human.website}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >Website</th
        >
        <td><a href={data.human.website}>{data.human.website}</a></td>
      </tr>
    {/if}
    {#if data.human.twitter}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >Twitter</th
        >
        <td><a href={data.human.twitter}>{data.human.twitter}</a></td>
      </tr>
    {/if}
    {#if data.human.aiGenerated}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >Generated By AI</th
        >
        <td>{data.human.aiGenerated}</td>
      </tr>
    {/if}
    {#if data.human.birthLocation}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >Birth Location</th
        >
        <td>{data.human.birthLocation}</td>
      </tr>
    {/if}
    {#if data.human.location}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >Location</th
        >
        <td>
          <ul class="flex flex-row">
            {#each data.human.location as location}
              <li>
                <Chip><a href="/search?query={location}">{location}</a></Chip>
              </li>
            {/each}
          </ul></td
        >
      </tr>
    {/if}
    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
      <th
        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
        >Created</th
      >
      <td title={data.human.createdAt}
        >{dayjs(data.human.createdAt).fromNow()}</td
      >
    </tr>
    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
      <th
        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
        >Last Updated</th
      >
      <td title={data.human.updatedAt}
        >{dayjs(data.human.updatedAt).fromNow()}</td
      >
    </tr>
  </table>
  <div class="text-left py-4">
    <SvelteMarkdown source={data.human.description} />
  </div>
  <div class="py-4">
    <ul class="flex flex-row">
      {#each data.human.tags as tag}
        <li>
          <Chip><a href="/search?query={tag}">{tag}</a></Chip>
        </li>
      {/each}
    </ul>
  </div>
</article>
