baseURL = "https://asianamericans.wiki"
languageCode = "en-us"
title = "AsianAmericans.wiki"
theme = "ananke"
enableGitInfo = true
googleAnalytics = "G-DNWC1SD6ZZ"
enableRobotsTXT = true
Paginate = 50
SectionPagesMenu = "main"

[frontmatter]
  lastmod = ['lastmod', ':git', 'date', 'publishDate']
  
[params]
  favicon = "/favicon.ico"
  site_logo = "/logo64.png"
  description = "The open source database of Asian Americans"
  twitter = "https://twitter.com/aapiwiki"
  github = "https://github.com/raymonstah/asianamericanswiki"
  custom_css = ["css/custom.css"]

[related]
  includeNewer = true
  threshold = 70
  toLower = true
[[related.indices]]
  name = 'tags'
  weight = 50
[[related.indices]]
  name = 'influencedBy'
  weight = 50
[[related.indices]]
  name = 'ethnicity'
  weight = 10

