// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api.proto

package server

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_MALE      Gender = 0
	Gender_FEMALE    Gender = 1
	Gender_NONBINARY Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
		2: "NONBINARY",
	}
	Gender_value = map[string]int32{
		"MALE":      0,
		"FEMALE":    1,
		"NONBINARY": 2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Now           string                 `protobuf:"bytes,2,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

type HumansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumansRequest) Reset() {
	*x = HumansRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumansRequest) ProtoMessage() {}

func (x *HumansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumansRequest.ProtoReflect.Descriptor instead.
func (*HumansRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

type HumansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Humans        []*Human               `protobuf:"bytes,1,rep,name=humans,proto3" json:"humans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumansResponse) Reset() {
	*x = HumansResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumansResponse) ProtoMessage() {}

func (x *HumansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumansResponse.ProtoReflect.Descriptor instead.
func (*HumansResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *HumansResponse) GetHumans() []*Human {
	if x != nil {
		return x.Humans
	}
	return nil
}

type Human struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Dob           string                 `protobuf:"bytes,4,opt,name=dob,proto3" json:"dob,omitempty"`
	Dod           string                 `protobuf:"bytes,5,opt,name=dod,proto3" json:"dod,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Ethnicity     []string               `protobuf:"bytes,7,rep,name=ethnicity,proto3" json:"ethnicity,omitempty"`
	Image         string                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Socials       *HumanSocial           `protobuf:"bytes,10,opt,name=socials,proto3" json:"socials,omitempty"`
	Gender        Gender                 `protobuf:"varint,11,opt,name=gender,proto3,enum=main.Gender" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Human) Reset() {
	*x = Human{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Human) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Human) ProtoMessage() {}

func (x *Human) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Human.ProtoReflect.Descriptor instead.
func (*Human) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *Human) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Human) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Human) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Human) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *Human) GetDod() string {
	if x != nil {
		return x.Dod
	}
	return ""
}

func (x *Human) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Human) GetEthnicity() []string {
	if x != nil {
		return x.Ethnicity
	}
	return nil
}

func (x *Human) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Human) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Human) GetSocials() *HumanSocial {
	if x != nil {
		return x.Socials
	}
	return nil
}

func (x *Human) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_MALE
}

type HumanSocial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instagram     string                 `protobuf:"bytes,1,opt,name=instagram,proto3" json:"instagram,omitempty"`
	X             string                 `protobuf:"bytes,2,opt,name=x,proto3" json:"x,omitempty"`
	Website       string                 `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	Imdb          string                 `protobuf:"bytes,4,opt,name=imdb,proto3" json:"imdb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanSocial) Reset() {
	*x = HumanSocial{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanSocial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanSocial) ProtoMessage() {}

func (x *HumanSocial) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanSocial.ProtoReflect.Descriptor instead.
func (*HumanSocial) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *HumanSocial) GetInstagram() string {
	if x != nil {
		return x.Instagram
	}
	return ""
}

func (x *HumanSocial) GetX() string {
	if x != nil {
		return x.X
	}
	return ""
}

func (x *HumanSocial) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *HumanSocial) GetImdb() string {
	if x != nil {
		return x.Imdb
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x04main\x1a\x1cgoogle/api/annotations.proto\"\x10\n" +
	"\x0eVersionRequest\"=\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03now\x18\x02 \x01(\tR\x03now\"\x0f\n" +
	"\rHumansRequest\"5\n" +
	"\x0eHumansResponse\x12#\n" +
	"\x06humans\x18\x01 \x03(\v2\v.main.HumanR\x06humans\"\xa0\x02\n" +
	"\x05Human\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x10\n" +
	"\x03dob\x18\x04 \x01(\tR\x03dob\x12\x10\n" +
	"\x03dod\x18\x05 \x01(\tR\x03dod\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1c\n" +
	"\tethnicity\x18\a \x03(\tR\tethnicity\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12+\n" +
	"\asocials\x18\n" +
	" \x01(\v2\x11.main.HumanSocialR\asocials\x12$\n" +
	"\x06gender\x18\v \x01(\x0e2\f.main.GenderR\x06gender\"g\n" +
	"\vHumanSocial\x12\x1c\n" +
	"\tinstagram\x18\x01 \x01(\tR\tinstagram\x12\f\n" +
	"\x01x\x18\x02 \x01(\tR\x01x\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\x12\x12\n" +
	"\x04imdb\x18\x04 \x01(\tR\x04imdb*-\n" +
	"\x06Gender\x12\b\n" +
	"\x04MALE\x10\x00\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x01\x12\r\n" +
	"\tNONBINARY\x10\x022\xa4\x01\n" +
	"\fHumanService\x12K\n" +
	"\aVersion\x12\x14.main.VersionRequest\x1a\x15.main.VersionResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/version\x12G\n" +
	"\x06Humans\x12\x13.main.HumansRequest\x1a\x14.main.HumansResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/humansB\n" +
	"Z\b./serverb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(Gender)(0),             // 0: main.Gender
	(*VersionRequest)(nil),  // 1: main.VersionRequest
	(*VersionResponse)(nil), // 2: main.VersionResponse
	(*HumansRequest)(nil),   // 3: main.HumansRequest
	(*HumansResponse)(nil),  // 4: main.HumansResponse
	(*Human)(nil),           // 5: main.Human
	(*HumanSocial)(nil),     // 6: main.HumanSocial
}
var file_api_proto_depIdxs = []int32{
	5, // 0: main.HumansResponse.humans:type_name -> main.Human
	6, // 1: main.Human.socials:type_name -> main.HumanSocial
	0, // 2: main.Human.gender:type_name -> main.Gender
	1, // 3: main.HumanService.Version:input_type -> main.VersionRequest
	3, // 4: main.HumanService.Humans:input_type -> main.HumansRequest
	2, // 5: main.HumanService.Version:output_type -> main.VersionResponse
	4, // 6: main.HumanService.Humans:output_type -> main.HumansResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
