#!/bin/bash
set -e

echo "Running go mod tidy..."
go mod tidy

echo "Running go mod vendor..."
go mod vendor

echo "Running golangci-lint..."
go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint run

echo "Running govulncheck..."
go run golang.org/x/vuln/cmd/govulncheck ./...

# Add changes to git
git add go.mod go.sum vendor/
