on: [push]
name: Publish asianamericans.wiki
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: pulimento/github-action-hugo-deploy-to-firebase@master
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}