on: [push]
name: Publish asianamericans.wiki
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: build
