name: ID Injector
on:
  push:
    branches: [main]
    paths:
      # only run when the source code changes or this file changes
      - "content/humans/**"
      - "functions/idinjector/**"
      - ".github/workflows/idinjector.yml"
jobs:
  id-injector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.0"

      - run: go run main.go --add-to-firestore
        env:
          FIRESTORE_CREDENTIALS: ${{ secrets.GCP_SA_HUMAN_ADDER }}
        working-directory: ./functions/idinjector

      - name: Pull Remote Changes
        run: git pull

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "system: inject human id"
          skip_dirty_check: false
          file_pattern: content/humans/*
          branch: ${{ github.ref }}
